title: Nazim Lachter
description: Développeur spécialisé dans la recherche et la réalisation d’idées originales

permalink: /article/:categories/:title

google_analytics: UA-31851675-4

repository: n4zim/n4zim.github.io

disqus:
  shortcode:

markdown: kramdown

gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
