title: Ariane Save

description: Ariane Save

repository: ariane5s/ariane5s.github.io

sass:
  style: compressed

markdown: kramdown

url: "https://aintnohenry.com"

exclude:
  - Gemfile
  - Gemfile.lock
